### ISSUE TITLE
plugin breaks WMS loading

### ISSUE THREAD

**Issue by alexfibrea** [NationalSecurityAgency/qgis-latlontools-plugin#15]
with: qgis 1: 2.18.13 + 14stretch

I have a problem with the extension, because I activate it I can not load a WMS (HTTPS) background.

I think it's a worry with pyhton, but have you ever had the case?

**Comment by hamiltoncj** [comment]
I have not seen any problems with QGIS 2.18.13 with HTTPS WMS services. I just tried this one and it works fine.

https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WMSServer?request=GetCapabilities&service=WMS

Could you check to see if there are any error messages from "Plugins->Python Console" or from the error messages by enabling "View->Panels->Log Messages Panel". Lat Lon Tools doesn't have anything to do with WMS so I cannot see how it could be a problem, but stranger things have happened.

**Comment by alexfibrea** [comment]
ok, I only have logs in "WMS"

This is also happening with other extensions

You can close the issue
