### ISSUE TITLE
Specify CRS error

### ISSUE THREAD

**Issue by antoniusz** [NationalSecurityAgency/qgis-latlontools-plugin#16]
Hi, 

I've got  this error, when wanted to use the Specify CRS in LatLon Digitize : Add Feature tool

An error has occurred while executing Python code: 

TypeError: QgsProjectionSelectionTreeWidget.setOgcWmsCrsFilter(): argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/latlontools/digitizer.py", line 205, in crsTriggered
    selector.setOgcWmsCrsFilter(self.inputCustomCRS)
TypeError: QgsProjectionSelectionTreeWidget.setOgcWmsCrsFilter(): argument 1 has unexpected type 'str'

Python version: 3.6.5rc1 (default, Mar 14 2018, 06:54:23) [GCC 7.3.0] 
QGIS version: 3.0.2-Girona Girona, a84084cf91

**Comment by hamiltoncj** [comment]
@antoniusz I believe I have fixed the problem with version 3.0.14 of the plugin. Sorry I didn't notice this bug report sooner. Let me know if you have any further problems.
