### ISSUE TITLE
Can't add a point in MULTIPOINT layers

### ISSUE THREAD

**Issue by Vitruvius21** [NationalSecurityAgency/qgis-latlontools-plugin#20]
I've written about it [at stackexchange](https://gis.stackexchange.com/questions/289539/lat-lon-digitize-tool-not-working-with-multipoint-in-qgis) and will repeat here as well.

"Lat Lon Digitize" tool doesn't work with **MULTIPOINT**, it works only with **POINT** layers.
Is it a bug?

**Comment by hamiltoncj** [comment]
Thank you for letting me know. That shouldn't be hard to fix. I will probably have a new update by tomorrow or early next week.

**Comment by hamiltoncj** [comment]
@Vitruvius21 I think I have fixed the problem. For QGIS 2 the version is 1.1.1 and for QGIS 3 the version is 3.1.2. Let me know if you have any other problems.
