### ISSUE TITLE
Points Digitizing Tool  Error to convert

### ISSUE THREAD

**Issue by OrenTims** [NationalSecurityAgency/qgis-latlontools-plugin#23]
I have a problem with "points and add features" . Longitude with error. 
I trying to add  385733.804N, 951555.739W
Latitude  all is OK!   385733.804N = "38.959390"
Longitude is wrong.   951555.739W = "-951555.739"

◦Degree, Minute, Second:
![lat-long](https://user-images.githubusercontent.com/43161519/45337674-a6a59900-b5a2-11e8-8311-7d782d23a820.JPG)
 385733.804N, 951555.739W (ddmmss.ssss, dddmmss.ssss) - In this format there must be 2 digits for latitude degrees, and 3 digits for longitude degrees.

**Comment by hamiltoncj** [comment]
@OrenTims Your example case is unique enough that I am able to make an exception for leaving off the first leading 0., but you cannot leave off 2 zeros in the case where there is only one significant degree digit.

I have updated the plugins so you should now see it parsing your example correctly.

**Comment by OrenTims** [comment]
I updated plagin and it working !
Thank you very much !
