### ISSUE TITLE
Copy Latitude, Longitude of the 4 corners of the window

### ISSUE THREAD

**Issue by fanou77** [NationalSecurityAgency/qgis-latlontools-plugin#24]
Hello,

Is it possible to have the same tools like "Copy Latitude, Longitude" but for copy the coordinates of the 4 corners of the active window.

Thanks.
Sorry for my poor English.
Stéphane

**Comment by hamiltoncj** [comment]
@fanou77 Thank you for your suggestion. I have been thinking about doing something like that. Do you prefer having the coordinates of the active window or would you prefer grabbing the coordinates by clicking and dragging a bounding box with the mouse?

How do you want the output coordinate string formatted? (left, bottom, right, top - or JSON, WKT) What delimiters do you want in between (comma, tab, space)?

Like the other tools I would try to make it as flexible as possible.

**Comment by fanou77** [comment]
Thanks for the answer.

For my personal use, i prefer the active window (but why not the both ;-) )

For example, something like that :+1:   6.18641023132388,48.64369386355367 6.187575100545294,48.64366269046158 6.187607540694417,48.64419493252551 6.186442659643811,48.64422610592086 6.18641023132388,48.64369386355367

Is it possible to add text before and after the coordinate? with french caracter like ï é è à.

Stéphane

**Comment by hamiltoncj** [comment]
@fanou77 For my interest, it is to define the bounding box with two points. This is often the way bounding boxes are specified. It looks like you want the actual rectangle with each point specified. What my thoughts are is to have multiple formats that the user can choose in the Settings. I can add what you want including beginning and ending text.

With my current project and the holiday season, it will probably be early January before I can finish this, but I may be able to get something working sooner especially if it is just the active window.

**Comment by fanou77** [comment]
Thanks it will be great.

**Comment by hamiltoncj** [comment]
@fanou77 I just updated Lat Lon Tools and it now has a canvas bounding box capture tool. You will need to go into the settings menu to specify which format you want captured. This capability is in version 3.1.7. Let me know how it works out for you.

**Comment by alexmodesto73** [comment]
I want to be able to paste the data in "Zoom to Lat Lon" is it possible?

**Comment by fanou77** [comment]
@hamiltoncj  Thanks for the uptade.

I tried the rectangle format in the BBOX Capture, it works fine but for my interest it's wrong.

I want to have coordinates like this, is it possible ? (x1,y1 x2,y2 x3,y3 x4,x4 x1,y1)
6.105143310104914,48.65685177363942 6.114378535765637,48.656610687756725 6.114629852373521,48.66082963224534 6.105393883010533,48.66107073672025 6.105143310104914,48.65685177363942

Thanks a lot

**Comment by hamiltoncj** [comment]
@alexmodesto73 

Zoom to Lat Lon just works with a single coordinate, not a bounding box. Is there interested in a bounding box zoom to capability?

**Comment by hamiltoncj** [comment]
@fanou77 

I have added your format as an additional BBOX format in the settings. Just select the one you want. The prefix and suffix work correctly with it. Look for version 3.1.8, but it may take a few minutes for QGIS to update its plugin catalog before it shows up. Let me know if this is what you needed.

Calvin

**Comment by hamiltoncj** [comment]
Yes I can do that, but it will be sometime in January before I will get back and work on it.

**Comment by hamiltoncj** [comment]
@fanou77 
I have added a prefix and suffix for Copy Latitude and Longitude. It is in Settings and is separate from the BBOX prefix & suffix setting. Let me know if this works for you. The version is 3.1.9. I just uploaded it and it usually take a few minutes before it shows up in the Upgradable plugins in QGIS.

**Comment by fanou77** [comment]
@hamiltoncj 
Sorry for the delay, i was in holidays.

The plugin works very well, just a last thing for the "copy Lattitude, Longitude" point, I don't need to have space betwen the X and Y coordinates (after the comma), something like  6.11630467715614,48.65469249856784

I think it's possible to modify directly in notepad the copyLatLonTool.py, can you tell me how?

**Comment by hamiltoncj** [comment]
You don't need to modify anything. Just go into the Lat Lon Tools settings and click on the "Capture & Display" tab. Under "Coordinate Capture Delimiter" select "Other" and then for "Other Delimiter" put a comma. I will probably make the change to have "Comma" and "Comma, Space" as options, but for now you can just use the Other delimiter.

**Comment by fanou77** [comment]
@hamiltoncj 
Yes :+1: 
Thanks you for job, the plugin works well for me :-)

Stéphane

**Comment by hamiltoncj** [comment]
@fanou77 
I went ahead and added just a single comma as one of the options for the coordinate capture delimiter. I think this solves everything so I am closing the ticket.

**Comment by fanou77** [comment]
Thanks.
It's seems that the "Coordinate digitis after decimal for Capture & Display" is not saved after closed and reloaded QGIS.
Ex: if i put 14, after reload QGIS, it's 8
Stéphane

    Le mardi 15 janvier 2019 à 21:00:06 UTC+1, C Hamilton <notifications@github.com> a écrit :  
 
 
Closed #24.

**Comment by hamiltoncj** [comment]
Thanks for noticing that. I released 3.1.11 which fixes the issue.
