### ISSUE TITLE
Add YX to LatLon converter and vice versa

### ISSUE THREAD

**Issue by Vitruvius21** [NationalSecurityAgency/qgis-latlontools-plugin#25]
I think this is a very needed tool, for instance, when you want to move a point (vertex) to exact coordinates you can do it only changing XY of vertex. But if you have only decimal coordinates (xx.xxxx yy.yyyyy) you need to use external applications to convert them in XY and then to paste them in vertex's XY. 

I have a python code for such conversion. 

```
import ogr, osr

pointLON = 41.660391636282924
pointLAT = 42.20147902194137

# Spatial Reference System
inputEPSG = 4326
outputEPSG = 32638

# create a geometry from coordinates
point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(pointLON, pointLAT)

# create coordinate transformation
inSpatialRef = osr.SpatialReference()
inSpatialRef.ImportFromEPSG(inputEPSG)

outSpatialRef = osr.SpatialReference()
outSpatialRef.ImportFromEPSG(outputEPSG)

coordTransform = osr.CoordinateTransformation(inSpatialRef, outSpatialRef)

# transform point
point.Transform(coordTransform)

print (point.GetX(), point.GetY())
```
This works in reverse direction too.
If you have time and will adding of this function will make your tool even more popular and cool! :)

**Comment by hamiltoncj** [comment]
I'm not exactly sure what you are asking for. Are you asking for some dialog box where you can paste in a coordinate in some format and then convert it to another textual format or are you asking to be able to click on an existing point feature and move it to a new location based on a textual coordinate in some format?

**Comment by Vitruvius21** [comment]
Both of them are good options. For some, only "converter" will be useful, for some "precise mover" and for others all of them. I can't ask you to do everything (it's your time&energy) but I think these features are missing in QGIS. And users will be pleased to see any or both of them.

**Comment by hamiltoncj** [comment]
I like your ideas and will try implementing them as I have time.

**Comment by hamiltoncj** [comment]
@Vitruvius21 
Today I put out Lat Lon Tools 3.3.0. It now has a 'Coordinate Conversion' tool. Any feedback would be appreciated.

**Comment by Vitruvius21** [comment]
@hamiltoncj thank you! It is awesome. The converter is even more advanced than I expected.
