### ISSUE TITLE
Custom CRS for 'Zoom to' not persistent

### ISSUE THREAD

**Issue by Tjeu** [NationalSecurityAgency/qgis-latlontools-plugin#26]
When you set a custom CRS for Zoom to it is not remembered when you restart QGIS.
![image](https://user-images.githubusercontent.com/11708371/53235356-ea441900-3691-11e9-9d57-9993fe72141b.png)

**Comment by hamiltoncj** [comment]
@Tjeu 
This has been fixed in Lat Lon Tools version 3.1.12. It might take a few minutes before the plugin repo will show that it is available in QGIS. Let me know if you have any other problems.

**Comment by Tjeu** [comment]
Thank you for the quick reply. 
It seems that it is not working yet. It remembers the custom CRS when I go to settings, but when I start QGIS and open the project it is still like this:
![image](https://user-images.githubusercontent.com/11708371/53667007-06d2e900-3c70-11e9-89fb-2d6b7797a9d6.png)
I thought it might be just the text, but when entering Easting and Northing it is not excepted. Still only lat, lon is allowed.

**Comment by hamiltoncj** [comment]
@Tjeu 
I think I have it fixed this time in version 3.1.13. Let me know if you have any other problem.

**Comment by Tjeu** [comment]
Works like a charm!
