### ISSUE TITLE
Add ability to input MGRS under multi location zoom

### ISSUE THREAD

**Issue by VIRG2019** [NationalSecurityAgency/qgis-latlontools-plugin#28]
Working with QGIS, I have been trying to find an open-source plugin that is as close to Geo Rover Locus Track, and Lat Lon Tools is very similar, except that I primarily work with MGRS coordinates. Being able to add MGRS coordinates in Multi Location Zoom would significantly enhance workload efficiency.

**Comment by hamiltoncj** [comment]
@VIRG2019 
I updated Lat Lon Tools (3.1.17) to include MGRS and Plus Codes in the multi zoom enter coordinate text box. The MGRS coordinate will not be displayed in MGRS format as it will be converted to a latitude and longitude. Hopefully this will help you out.

To select MGRS input go to Settings and the Multi-zoom tab. Under "CRS/Projection of input coordinates" select MGRS. Let me know how this works out for you.

**Comment by VIRG2019** [comment]
@hamiltoncj 
I was able to download, install and switch the CRS to "MGRS" under the Multi-zoom tab. However, When inputting MGRS it still said the coordinates were invalid. Of note, it stated: "invalid coordinate" when inputting the MGRS as, for example, 41SPU1234512345. If any spaces were added or any other type of MGRS format was used it gave the error: "Invalid coordinate. Perhaps Comma separators between fields were not used." All other MGRS functions continued to work as intended. When getting the errors, I attempted to use the copy/paste function to paste directly in to the multi zoom input as well as manually inputting MGRS coordinates and neither worked. I tried using the newest version (3.1.17) on QGIS 3.6 and 3.0.3.

**Comment by hamiltoncj** [comment]
Sorry about that. I had it working and then added plus code support and broke the MGRS input. I have updated the plugin repo with version 3.1.18. It might take a few minutes for qgis.org to update their files so that it reports this version is available. Let me know if that fixes the problem.

**Comment by VIRG2019** [comment]
Problem fixed! Thank you for the quick turn around on updating and subsequently fixing the plugin. Everything works as intended.
