### ISSUE TITLE
Custom CRS for 'Capture & Display' and for 'Multi-zoom' not persistent

### ISSUE THREAD

**Issue by protatg** [NationalSecurityAgency/qgis-latlontools-plugin#32]
The setting for a custom CRS in above mentioned areas are not persistent. Probably the same as with issue #26

**Comment by hamiltoncj** [comment]
@protatg 
Thank you for your input and yes you are correct. I will add persistence to these as well although I am currently working on another project so it might take me several days before I get to this. Hopefully, I will have it done by the end of the week.

**Comment by hamiltoncj** [comment]
@protatg 
I put out release 3.3.0. The CRS is now persistent for Multi-zoom and the coordinate capture. Please test it to make sure it works the way you want it to.

**Comment by protatg** [comment]
Perfect. It works exactly as we need it. Thank you so much!
