### ISSUE TITLE
Add support for snapping

### ISSUE THREAD

**Issue by simo78** [NationalSecurityAgency/qgis-latlontools-plugin#33]
It seems that the plugin does not support snapping, even though enabled via "Project > Snapping Options" menu. Please consider adding support for snapping.

**Comment by hamiltoncj** [comment]
@simo78 
Are you suggesting this for the Lat Lon Digitize tool? That seems to be the only capability that would make sense to have snapping added to. If there is something else please explain how you would like it to work.

**Comment by simo78** [comment]
My apologies for giving you somewhat vague details on this feature request. 

The issue is related to "Copy Latitude, Longitude" tool. For example, I would like to get exact coordinates of a vertex, but without snapping it is difficult to get exact coordinates of a vertex (mouse pointer could easily be 1 pixel off the vertex). Another need is to get coordinates of the location where two polygon segments intersect. 

My use case is related to aviation. I am a private pilot working on a free geospatial model of our national airspace structures. Very often I need to quickly get the exact coordinates of e.g. a prohibites airspace, and "Copy Latitude, Longitude" tool would be perfect for this if it supported snapping. 

Thanks for your time and effort.

**Comment by hamiltoncj** [comment]
Thanks for that information. This seems like a useful function so I will take a look at what it will take to implement it next week. I don't know if the QGIS snapping includes intersection points where polygons intersect, but I will investigate it.

**Comment by hamiltoncj** [comment]
I wanted to let you know that I am working on this request. I currently have it working, but want to give the user more feedback that it has locked onto a point so I am going to complete that part before I do a new release which may be sometime next week.

**Comment by hamiltoncj** [comment]
@simo78 
That took less time than I thought. This feature has been implemented in version 3.3.3. It may take a few minutes before QGIS will report that a new version is there. Please let me know what you think.

**Comment by hamiltoncj** [comment]
@simo78 
I introduced a bug into version 3.3.3 so I fixed it and have now pushed out 3.3.4.

**Comment by simo78** [comment]
I have tested the snapping feature on the "Copy Latitude, Longitude" tool. It seems to work perfectly, both on a vertex and also on polygon intersections. I believe you can close this issue. Your effort on this plugin is highly appreciated!
