### ISSUE TITLE
Feature request : multiples buttons external map

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#36]
Is it possible to have two buttons to open external links?

Example:
Button 1: google maps
Button 2: mapillary

objective open one or the other, depending on the coverage

**Comment by hamiltoncj** [comment]
I guess I could consider having the left mouse open up one and the right mouse another. Is that what you are thinking of? Would that work?

**Comment by alexmodesto73** [comment]
Good idea !

**Comment by hamiltoncj** [comment]
I have made the left and right mouse buttons select different maps. Go to the Settings window to configure how you want these to work. Let me know if this works as expected. The new version of software is 3.3.7. It may take a few minutes to propagate through the system before it is discoverable.

**Comment by hamiltoncj** [comment]
I believe I fulfilled this feature request so I am going to close this ticket.
