### ISSUE TITLE
Zoom To -  Zoom level

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#37]
Zoom To

Is it possible to have a choice on the zoom level?

1) Paste coordinates
2) Zoom to 1:5000

**Comment by hamiltoncj** [comment]
The Zoom To does not change the zoom level. There is already that capability with the scale drop down that is in QGIS. I don't really want to replicate an existing capability.

**Comment by hamiltoncj** [comment]
Because QGIS already has a method of doing this I am not planning on adding this capability and am going to close the ticket.
