### ISSUE TITLE
Open ID OSM Editor

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#38]
add an optional button
to open the OSM online editor

ex:
https://preview.ideditor.com/master/#6map=18.00/-6.17730/39.19930&background=fr.ign.bdortho&disable_features=boundaries&id=n5189512929&map=14.90/45.5183/6.5846&overlays=BANO&photo_overlay=mapillary-map-features

**Comment by hamiltoncj** [comment]
That is a good idea. I will try to add it next week.

**Comment by hamiltoncj** [comment]
I have added two iD maps as well as have the left and right mouse buttons select different maps. Go to the Settings window to configure how you want these to work. Let me know if this works as expected. The new version of software is 3.3.7. It may take a few minutes to propigate through the system before it is discoverable.

**Comment by hamiltoncj** [comment]
I believe I solved this issue so I am going to close the ticket.
