### ISSUE TITLE
feature request : paste lat/lon into control + K window

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#39]
Suggestion:

Rather than having a panel: zoom to latlon
Would not it be possible to have a regexp in Control + K to detect a geo: lat / lon position?

![image](https://user-images.githubusercontent.com/34935886/68286224-056c8280-0081-11ea-87ca-d0031573cfef.png)

**Comment by hamiltoncj** [comment]
You certainly have some great ideas and I am sure this could be done. I don't know how much work this would be, but I will at least investigate it and see if I would have the time to do it.

**Comment by hamiltoncj** [comment]
This will not give the flexibility that you get with a separate panel and I think it requires a designator to specify that you are entering a coordinate something like 'g 45.5555, 6.2619' or 'utm 15S 525698.27 13717565.00'. I think this would need to be a separate ability and not a replacement for the zoom to dialog box. Personally I would not want to enter an extra character with a coordinate. Unless there is a justifiable need for this, it is probably not something I would add.

**Comment by hamiltoncj** [comment]
I'm going to close this feature request, because this does not have the functionality that the core lat lon tools zoom tool provides and is not what I want to do with the plugin, but thanks for the suggestion.
