### ISSUE TITLE
feature request : shortcut capture gps

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#40]
Rather than clicking the Copy Coordinates button.

Is it possible to assign a keyboard shortcut?

scenario:
Key pressed (keyboard shortcut)

=> enable the coordinate copy feature
=> click
=> finished, coordinated in the clipboard

**Comment by hamiltoncj** [comment]
@alexmodesto73 
If you go to "Settings->Keyboard shortcuts..." you can search for "Copy/Display Coordiate" and then assign a keyboard shortcut to it. Now by typing that key it will automatically allow the copying of a coordinate to the clipboard. It is best to use what QGIS already has. Is this what you needed or were you thinking of something more?

**Comment by alexmodesto73** [comment]
thanks for the tip! I closed the issue
