### ISSUE TITLE
Feature Request: ability to add custom external web map providers

### ISSUE THREAD

**Issue by spaceof7** [NationalSecurityAgency/qgis-latlontools-plugin#44]
I've modified the mapProviders.py file to add some web maps that we commonly use, but Id love a simpler way to add map providers so that our less tech savvy users can add some of the maps they want to use.

**Comment by hamiltoncj** [comment]
@spaceof7 
How would you like to see this work?

**Comment by spaceof7** [comment]
I hadnt thought about that in too much detail.  I vaguely recall a 2.x plugin(Qgis Web Connector) where you could enter the URL with placeholder for lat,lon and zoom in a text box, very similar to the strings used in mapProviders.py.

for instance: 
If I wanted to add King County, WA's iMap i can use [ArcGIS Online's URL parameters](https://doc.arcgis.com/en/arcgis-online/reference/use-url-parameters.htm):
https://gismaps.kingcounty.gov/iMap/?center=-122.446,47.435&level=8
Im imagining a text box where I could enter:
https://gismaps.kingcounty.gov/iMap/?center={lon},{lat}&level={zoom}

Now that I think about it, most of the maps Im connecting to( though not all) are state or local government sites that all use AGOL and therefore all use the same format for URL parameters.  so maybe instead of constructing a URL from scratch you could add a "zoom to AGOL map" option where the user just inputs the base URL?  That would definitely make it easier to use for our biologists.

I also wonder if it would be possible to use the expression builder to construct more complex URLs for services that want an extent, or coords in a different CRS or so you can use other URL parameters to open with specific layers, basemaps etc.  though that is possibly turning into something that should be handled in a seperate plugin.

**Comment by hamiltoncj** [comment]
@spaceof7 I am only working part time during COVID so it is taking more time than usual, but I plan on working on this request. I think it will be a good addition. Thanks for suggesting it.

**Comment by hamiltoncj** [comment]
@spaceof7 
I added Lat Lon Tools version 3.3.19. I had the ability to add personal map URLs. I changed how I specify the URL so that it uses {lat}, {lon}, and {zoom}. The URL you listed can be input as is.

Let me know what you think and whether you encounter any problems.

**Comment by spaceof7** [comment]
Thanks for adding this feature.  Ive been focused on other work but Ill try to get some time today or tomorrow to test this out.

**Comment by spaceof7** [comment]
Ive tested it out with a few different maps and its working  really well.  Thanks for adding the feature, it will really make my users happy!
