### ISSUE TITLE
Feature Request : Qgis URL

### ISSUE THREAD

**Issue by alexmodesto73** [NationalSecurityAgency/qgis-latlontools-plugin#45]
Hello,

A silly idea:

Have a type url:
latlong: //45.157558, 6.151008

Who opens QGIS and focuses on the position

This could be used in emails, wiki etc.
To make life easier for people who have to look at a geographic location.

**Comment by hamiltoncj** [comment]
It sounds like a cool idea, but I have no clue on how to implement the interaction between a web browser or e-mail client to launch QGIS and display the location.

**Comment by alexmodesto73** [comment]
Slack or zoom applications seem to be able to open a url

example: https://community.brave.com/t/xdg-open-error-when-trying-to-open-external-apps/115100

**Comment by hamiltoncj** [comment]
I am going to close this enhancement request because it is beyond the scope of the lat lon tools plugin and is beyond what I am asked to do.
