### ISSUE TITLE
Copy coordinate is WGS 84 by default

### ISSUE THREAD

**Issue by protatg** [NationalSecurityAgency/qgis-latlontools-plugin#46]
Hello,

The coordinate system of the 'Copy/Display Coordinate' Tool is always WGS 84 when first used. After opening and closing the settings without doing any changes it works fine with the project crs.

Also the settings of 'Multi-zoom', 'BBOX Capture' and the 'Converter' are not persistent again and a phyton error occurs when opening the settings.

**Comment by hamiltoncj** [comment]
This sounds like a problem with your system rather than Lat Lon Tools. Can you tell me what OS you are running, version of QGIS, and are you using the latest Lat Lon Tools?

**Comment by protatg** [comment]
I checked again with the LTR QGIS 3.10.6 and Lat Lon Tools 3.3.19. Only if in the 'Capture' settings a Custom CRS is defined it copies WGS 84 coordinate values to the clipboard when first used. With a Project CRS setting it works well.

The non-persistent settings and the python error are problems of my installation.

**Comment by hamiltoncj** [comment]
I was able to replicate the problem and I will work on a fix. Thanks for reporting this.

**Comment by hamiltoncj** [comment]
I have released version 3.3.20 which has the fix for this bug. Let me know if you have any other issues.

Thanks!

**Comment by protatg** [comment]
It works fine. Thank you
