### ISSUE TITLE
DMS format

### ISSUE THREAD

**Issue by inouterer** [NationalSecurityAgency/qgis-latlontools-plugin#47]
Hello!
What format should the DMS coordinates be in? I try to convert fields to points without success.
Point1        70 20 42.13        68 51 28.8

**Comment by hamiltoncj** [comment]
@inouterer 
Lat Lon Tools documentation gives examples of how DMS strings should be formatted. The number string you are using, cannot be turned into coordinates without some additional information.  For example, adding N,S,E,W to each coordinate would fix the problem, but there are other ways to format them as well. It depends on what you are trying to do.

**Comment by hamiltoncj** [comment]
Closing ticket due to inactivity.
