### ISSUE TITLE
Multi-location zoom select multiple entries and delete and display them

### ISSUE THREAD

**Issue by hamiltoncj** [NationalSecurityAgency/qgis-latlontools-plugin#5]
[IDEA ?]
If you make the table (with label and coordinates) in Multi-Location
Zoom multi-line selectable, you can get rid of the 'Show all markers'
checkbox. As you will show all selected rows in the table.
This would also make it possible to remove ALL rows in the table in one
go (using current red trash-button, which currently removes just 1 item
at a time).

**Comment by Dgreen604** [comment]
It's a good idea that solves the issue and adds greater value with the solution.
