### ISSUE TITLE
external map settings error

### ISSUE THREAD

**Issue by miet-t** [NationalSecurityAgency/qgis-latlontools-plugin#50]
Can't define additional external map providers - error message appears during openning settings form: 
"File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\latlontools\settings.py", line 552, in showEvent for item in settings.userMapProviders: TypeError: 'NoneType' object is not iterable".
Built-in map providers list is empty.

plugin version 3.3.22, 
QGIS 3.10.9 x64, 
Windows 10

![error](https://user-images.githubusercontent.com/60602972/92534896-4059bc80-f236-11ea-820f-f6c2bb844dff.png)

![message](https://user-images.githubusercontent.com/60602972/92535085-b65e2380-f236-11ea-90ca-4b2d62429535.png)

**Comment by hamiltoncj** [comment]
Thanks for noticing that. I just deleted that new release until I figure out how I introduced that bug and fix it. Hopefully by the end of today I will have a fix.

**Comment by hamiltoncj** [comment]
I just put up lat lon tools 3.4.0. It may take a few minutes for it to show up as a new release. I think this problem has been fixed. Let me know if you find any other issues.

**Comment by miet-t** [comment]
Yes, it works fine now. Great job, thanks.

As suggestion for improvement: it would be nice to have option for MGRS precision (1m/10m/100m/1km/10km) in Capture and Coordinate Conversion.
