### ISSUE TITLE
copy to clipboard = corrupted data?

### ISSUE THREAD

**Issue by jipexu** [NationalSecurityAgency/qgis-latlontools-plugin#51]
Hi
When i use the copy to clipboard command of the conversion menu they are some invisible characters (at the front of lat and long coord) who are also copied !?

On my mac i use copy to clipboard => paste on  a filemaker db field=> export for mysql => (when checking the db on phpmyadmin i can see those character as ? or ?? at the front of lat and long coord)

at the end this break the js of my (openlayer6)  map application  ...

So the question is why we get those characters are they usefull ??

Thanks

**Comment by hamiltoncj** [comment]
@jipexu 
There shouldn't be any extra characters. Can you tell me what your settings are when you do the copy? I will investigate to see what is going on.

**Comment by hamiltoncj** [comment]
@jipexu 
In the Lat Lon Tool capture settings, there is a field for a prefix and suffix. Can you verify that those fields have no characters in them?

**Comment by jipexu** [comment]
ok let me check ..

**Comment by jipexu** [comment]
<img width="752" alt="Capture d’écran 2020-10-20 à 16 46 43" src="https://user-images.githubusercontent.com/328101/96603488-59a15e80-12f4-11eb-8488-3d089c8a5c41.png">

**Comment by hamiltoncj** [comment]
@jipexu 
I was thinking you were using the Capture capability and not the converter. Can you tell me which copy function you are using or does it happen when all of them?

**Comment by jipexu** [comment]
i use the first one (decimal degree) if i use the bouton or directly from my computer ii got those

**Comment by hamiltoncj** [comment]
I am having a hard time replicating this behavior, but I am on a Windows 10 OS. What version of QGIS are you using and what version of Lat Lon Tools? This may be a mac QGIS issue. Could you check some of the other coordinates to see if does the same thing. Also check to see if the "Copy/Display Coordinate" does the same thing or not. One thing I could try is to include a strip white space from the coordinate string before I paste it to the clipboard. In reality there shouldn't be any white space on it, but I will investigate further.

**Comment by jipexu** [comment]
i use QGIS 3.14 and the last version of the pluggin ... yes it is very strange i will try to test but not easy to know if it is or not invisible char ... because i see them only when they arrive in my mysql db ...
so probably is a only mac issue ?..?
