### ISSUE TITLE
Paste button please

### ISSUE THREAD

**Issue by ianengelbrecht** [NationalSecurityAgency/qgis-latlontools-plugin#58]
This is a great tool and central our georeferencing workflow here at the [NSCF.](nscf.org.za) It would be amazing if you could add a little paste button to the Zoom to Coordinates tool, just to save us the trouble of pressing Ctrl+V each time :-P This is of course a feature request and not an issue.

**Comment by hamiltoncj** [comment]
@ianengelbrecht  That was a great idea. I have released Lat Lon Tools version 3.5.2 with this implemented. Let me know if this works for your needs.

**Comment by ianengelbrecht** [comment]
Works like charm, greatly appreciated!
