### ISSUE TITLE
Expose PlusCode functions to Field Caclulator / Espression Builder

### ISSUE THREAD

**Issue by agiudiceandrea** [NationalSecurityAgency/qgis-latlontools-plugin#59]
Let the PlusCode functions be available in the Field Caclulator / Espression Builder.

**Comment by hamiltoncj** [comment]
Thank you for your suggestion. It will be fairly easy to enable the functions in the field calculator so I will put this on my to-do list although it may be several weeks before I have the time to get to it.

**Comment by hamiltoncj** [comment]
@agiudiceandrea  I released Lat Lon Tools 3.5.5. I have added two field calculator functions; to_pluscode and from_pluscode. Let me know if that completes this ticket.

**Comment by agiudiceandrea** [comment]
@hamiltoncj why this GitHub repository is outdated? The latest release available is 3.5.3, while on plugins.qgis.org is 3.5.5.

**Comment by agiudiceandrea** [comment]
@hamiltoncj It seems working.

Anyway the description of `from_pluscode` seems incorrect: "Calculate the Plus Code coordinate from latitude and longitude coordinates."
https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/blob/0180592819ede0471d6578c0cbd321ee2220e69b/latLonFunctions.py#L316-L319

Moreover I'd suggest specifying that the coordinates are expected to be WGS84 (isn't it?).

**Comment by hamiltoncj** [comment]
@agiudiceandrea I fixed the documentation and released 3.5.6.
