### ISSUE TITLE
Lat Lon Tools expression to be used in array foreach

### ISSUE THREAD

**Issue by roelsantiago** [NationalSecurityAgency/qgis-latlontools-plugin#61]
Is there a way to use the ddmmss expression instead of to_dms inside the array for each? see expression below:

replace (
    array_to_string (
        array_foreach (
            generate_series (1, num_points( $geometry)-1),
            to_dms (x(point_n( $geometry,@element)),'y',2, 'suffix')  || ' ' || 
            to_dms(y(point_n( $geometry,@element)),'x',2, 'suffix')  || '\n'
    )),
    ',',''
)

The objective is to come up with an output of packed coordinates (Lat/Long) instead of the coordinates with symbols.

**Comment by hamiltoncj** [comment]
You could do something like this.

replace (
array_to_string (
array_foreach (
generate_series (1, num_points( $geometry)-1),
ddmmss(y(point_n( $geometry,@element)), x(point_n( $geometry,@element)), 'yx',0,'')
)),
',',''
)

**Comment by hamiltoncj** [comment]
You can use

transform(geometry,source_auth_id,dest_auth_id)

Perhaps I should add an optional crs parameter to ddmmss to make it easier.

**Comment by hamiltoncj** [comment]
I updated Lat Lon Tools to version 3.5.8 so you can now add an optional CRS parameter like this:


ddmmss(3301866.78, -9081576.13, 'yx', 0, ', ',  'EPSG:3857')

**Comment by roelsantiago** [comment]
Dear Sir,

Can you show how to combine the transform expression in the below expression

replace (
array_to_string (
array_foreach (
generate_series (1, num_points( $geometry)-1),
ddmmss(y(point_n( ***@***.*** <https://github.com/element>)),
x(point_n( ***@***.*** <https://github.com/element>)), 'yx',0,'')
)),
',',''
)

Thanks and kind regards,

Roel

**Comment by roelsantiago** [comment]
Dear Sir,

Good morning!

Hope this email finds you well,

I would like to resurface this email thread on the expression to get the
coordinate conversion in array_foreach. This time I need them in decimal
degree instead of ddmmss (needed to digest the data in AIXM gml code which
requires decimal degrees instead of ddmmss). I've checked the
documentations, there was no expression for decimal degrees.

Appreciate your assistance on the matter.

Kind regards,

Roel

**Comment by hamiltoncj** [comment]
@roelsantiago Usually it is best to open a new ticket, but I will reopen this one. I didn't add a decimal degree routine because you can naturally get the x and y decimal coordinates from $x and $y. If you need to you can transform your coordinate first. I don't know if it is worth adding a Lat Lon Tools expression to format the entire string all at once.

**Comment by hamiltoncj** [comment]
@roelsantiago I decided to add two more expressions and should have a new Lat Lon Tools release before the end of the week.

**Comment by roelsantiago** [comment]
Dear Sir,

This is a welcome news for us in the aeronautical information management
domain as we can easily extract the geographic extent of a layer (for
aerodrome mapping element such as taxiway, runway, apron and aircraft
stands) in local coordinate system  and transform to aixm data using QGIS
expression (especially array_foreach expression). Currently, what we are
doing is to transform the layer to wgs84.and work from there.

Your plugin tools are really helpful to our use-case.

Kind regards,

Roel

**Comment by hamiltoncj** [comment]
I released Lat Lon Tools 3.6.2. There is a new function called ll_dd. Let me know how it works out for you.

**Comment by roelsantiago** [comment]
Dear Sir,

Got it, Superb addition to the tools!. I will recommend my colleagues in
the AIM Community to use your plugin..

Muchas gracias!

Kind regards,

Roel

**Comment by hamiltoncj** [comment]
@roelsantiago Glad it works for you.
