### ISSUE TITLE
Coordinates conversion code

### ISSUE THREAD

**Issue by ianengelbrecht** [NationalSecurityAgency/qgis-latlontools-plugin#62]
Could I ask if the code you use for converting coordinates is publically available as a standalone Python module (I'm assuming it's Python)? I wrote a [coordinates converter for Javascript](https://www.npmjs.com/package/geo-coordinates-parser) and it would be great to have something like this for Python. Many thanks!

**Comment by hamiltoncj** [comment]
@ianengelbrecht There are a number of different parts to the code. Some of them are public python modules, such as MGRS, Google Plus code, Geohash, & Maidenhead. There are other parts such as parsing of latitude and longitude coordinates that I wrote. I have not made that into a separate library. My UTM code requires the PyQGIS library.

I guess the overall answer to your question is no I don't have a standalone Python module. Some parts could be modularized, but other parts require PyQGIS. Is there a particular part of this you are interested in?

**Comment by ianengelbrecht** [comment]
My apologies that I did not reply @hamiltoncj, I meant to. Thank you for the response. I'm specifically interested in lat/long conversion. If that is standalone and coule be modularized easily it would be valuable to have. If not though please don't go to the trouble, it might simpler to convert my javascript code to Python.
