### ISSUE TITLE
Virtual field and coordinate capture results do not match.

### ISSUE THREAD

**Issue by TyHol** [NationalSecurityAgency/qgis-latlontools-plugin#63]
I have a point layer with one feature at location 82700, 86000 (x,y, EPSG:29902) , I'm trying to add a virtual field with long lat using 
 dm( $x ,$y,'xy',4,True, True,',','EPSG:29902'), the resultant long lat [009° 39.6057' W,51° 59.1106' N] value is different from that obtained using the coordinate capture tool [009° 42.55415' W, 52° 00.84801' N]. 
Both the project and the layer are EPSG:29902.
![image](https://user-images.githubusercontent.com/96470691/146908050-27873152-fdb0-448e-becb-ae90023e7976.png)

I feel I'm doing something wrong, any pointers would be appreciated.
Many thanks.

**Comment by hamiltoncj** [comment]
@TyHol 
Thanks for letting me know. This appears to be a bug. I will get back to you with an update, but I am out of the office most of the time between now and the new year.

**Comment by hamiltoncj** [comment]
@TyHol 
Actually, the algorithms are correct. The dm algorithm expects the coordinates in y, x order. So if you input

dm( $y ,$x,'xy',4,True, True,',','EPSG:29902')

you will get the correct results. The 'xy' field specifies the output order - not the input order.

**Comment by TyHol** [comment]
Thanks a million for that and all the work you've put into the plugin. Have a good break and a happy new year.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
