### ISSUE TITLE
Unable to remove Copy Extent Button from toolbar

### ISSUE THREAD

**Issue by jfbourdon** [NationalSecurityAgency/qgis-latlontools-plugin#64]
Unchecking the appropriate box in the Interface Customization options doesn't remove the Copy Extent buttons from toolbar. I tried various combinations of checked/unchecked levels without any success. However, unchecking a single button like _latLonToolsCopy_ or _latLonToolsDigitize_ works as it should. I wonder if it has to do with the fact that the level labeled _Copy Extents to Clipboard_ and its upper-level aren't named.

![unchecked_toolbar](https://user-images.githubusercontent.com/32580398/147720570-b9bfc5ae-a8aa-40b0-afd3-570f90708472.png)

My current workaround is to comment out the following lines:
https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/blob/8f635b45cee5e9c7ab0d3ab5507e561dce8baba0/latLonTools.py#L106-L112

Tested in QGIS 3.22.2 with Lat Lon Tools 3.5.9

**Comment by hamiltoncj** [comment]
@jfbourdon Giving the top level a name did the trick. You should be able to remove it from the toolbar now. The new version is 3.5.10. It looks like once you make changes you need to exit QGIS and relaunch it to see the change.

**Comment by jfbourdon** [comment]
Thanks, all fixed now.
