### ISSUE TITLE
Lat Lon Digitize problem

### ISSUE THREAD

**Issue by opalina79** [NationalSecurityAgency/qgis-latlontools-plugin#65]
when I add a new point the tool inserts a new point feature and the attribute but at the same time modifies the attributes of the first record, overwriting them with those just inserted.

**Comment by hamiltoncj** [comment]
I tested "Lat Lon Digitize" which I think you are probably talking about. Please verify that is correct. I was not able to replicate the problem you are seeing. Can you provide more information? What operating system and what version of QGIS you are using? What type source layer you are trying to add points to? What are the steps to replicate this problem?

**Comment by opalina79** [comment]
Hi, thanks for replying. My operating System is Win11 (but the problem was on win10 too). Qgis ver. 3.20.3. with installed the last version of Lat Lon Tools plugin. 
I've a point layer, and i must add new point (new Meteo-Idro station). I active the editing of the point layer, click on Lat Lon Digitize, insert the lattitude and longitude Coordinates and the form for attribute insert appear. So I add the relative attributes and then stop editing, I save the changes. When I open the attribute table I find the new record and the record ID = 0 overwrited (the location on map is correct).
I'll attach a pdf containing the screenshots of the steps.

**Comment by opalina79** [comment]
Point Layer called "Lista Sensori TOTALE"
![1](https://user-images.githubusercontent.com/95290448/156398574-ab1ec554-025b-420e-9523-d058be43a41c.png)

Start Editing
![2](https://user-images.githubusercontent.com/95290448/156398591-58491f24-fb0c-49ea-9ec2-01ac9620add6.png)

I digit LAT LON Coordinates
![3](https://user-images.githubusercontent.com/95290448/156398599-5bda7804-1ffc-46e4-b51f-be2e0407362e.png)

Fill in the form
![4](https://user-images.githubusercontent.com/95290448/156398601-782a2cac-c948-42f1-984b-a41e9b73051c.png)

I save the changes
![5](https://user-images.githubusercontent.com/95290448/156398608-5e24b171-91a8-47cf-815c-659dd6850a8c.png)

Now I find the new record and the record ID=0 overwrite with Attribute of last record added.
![6](https://user-images.githubusercontent.com/95290448/156398612-41eaad13-fea1-42d6-ba7e-091ce3901f3d.png)
![7](https://user-images.githubusercontent.com/95290448/156398613-cc297647-05c9-4056-9ff3-514d0af2f921.png)

**Comment by hamiltoncj** [comment]
I just installed the same version of QGIS you are using, but have not been able to duplicate the problem. Is your source file a Shapefile, GeoPackage, or some database?

**Comment by opalina79** [comment]
Hi, it's a shp file.

Il gio 3 mar 2022, 15:37 C Hamilton ***@***.***> ha scritto:

**Comment by hamiltoncj** [comment]
[latlontools-3.6.3-beta.zip](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/files/8179072/latlontools-3.6.3-beta.zip)
I have attached a new plugin. Can you test it to see if it works? I rewrote that section of code.

**Comment by hamiltoncj** [comment]
I believe that this is now fixed as of Lat Lon Tools 3.6.3 which I just added to the qgis plugin repo. Let me know if you have any further problems.

**Comment by hamiltoncj** [comment]
I am going to close this issue. I believe the problem is solved, but if you find any other problems please let me know.

**Comment by opalina79** [comment]
Thank you. Now it seems to work correctly. Thank's for your job!

Il giorno lun 7 mar 2022 alle ore 15:02 C Hamilton ***@***.***>
ha scritto:
