### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by ratnanil** [NationalSecurityAgency/qgis-latlontools-plugin#66]
I get a `std::bad_alloc` error when trying to install this plugin. After which, QGIS crashes. Any idea why this could be?

![DeepinScreenshot_20220316073903](https://user-images.githubusercontent.com/12532091/158531283-c40363f8-0a21-439c-83d5-5698d248b4c5.png)

When I check my QGIS Version, it says:

```
QGIS version: 3.24.0-Tisler
QGIS code revision: 6b44a42058
Qt version: 5.12.8
Python version: 3.8.10
GDAL/OGR version: 3.4.0
PROJ version: 8.2.0
EPSG Registry database version: v10.038 (2021-10-21)
GEOS version: 3.10.1-CAPI-1.16.0
SQLite version: 3.31.1
PDAL version: 2.2.0
PostgreSQL client version: 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version: 5.0.1
QWT version: 6.1.4
QScintilla2 version: 2.11.2
OS version: Ubuntu 20.04.4 LTS




Active Python plugins: quick_map_services 0.19.28
SentinelHub: 2.0.0
db_manager: 0.1.20
processing: 2.12.99
grassprovider: 2.12.99
MetaSearch: 0.3.6
sagaprovider: 2.12.99
```

**Comment by hamiltoncj** [comment]
I have not heard about an error like that before. I personally don't have an Ubuntu machine to test, but I know Lat Lon Tools is used heavily by the Ubuntu community and I would have expected to have been contacted well before now if others were having a similar problem. To me this sounds like a QGIS problem. You might try moving or removing your QGIS profile which will make it like you freshly downloaded QGIS for the first time. Then install Lat Lon Tools and see if you get the same result. Try installing some other plugins. Do you get that error message when installing other plugins?

I don't trust any of the QGIS 3.x.0 (3.24.0) releases. They frequently have bugs and this may be one of them. Have you tried QGIS 3.22.4? It is a long term release and should be stable.

**Comment by ratnanil** [comment]
Thank you for your answer and sorry for the long delay. I tried with different versions of QGIS, all with the same result (`std::bad_alloc`). However, a fresh installation of Ubuntu with 3.24.1 did resolve the problem!

**Comment by pka** [comment]
Same error here. I can't activate the plugin with QGIS 3.24.1 on Ubuntu Linux. I'm not able to get a stack trace, only the message `Critical: Caught unhandled std::exception:  std::bad_alloc`

**Comment by greyeagle** [comment]
Same problem for me with Ubuntu and QGIS 3.16.11-Hannover
I tried starting up with a fresh profile not using any other plugins. Problem started a few weeks ago driving me up the wall. I use LatLon tools all the time (great tool and thank you at this point)
![image](https://user-images.githubusercontent.com/9130652/181520179-34a4bf2c-20a7-4f73-966a-52cfce83667c.png)

**Comment by hamiltoncj** [comment]
I have no idea why this is occurring. I don't use Ubuntu so it makes it difficult to debug. As you can see one individual did a fresh install of Ubuntu and it solved the problem. I have queried the QGIS developers group to see if anyone else has seen this or would know why it is occurring. Do you have any problem with other plugins installed without Lat Lon Tools?  Have you tried older versions of Lat Lon Tools? Here are some different versions if you click on the Versions tab.

https://plugins.qgis.org/plugins/latlontools/

**Comment by greyeagle** [comment]
I just upgraded from Ubuntu 20.04 to Ubuntu 22.04 and thus got to QGIS 
3.22.4-Białowieża
did a fresh install of the plugin and now the issue is gone. I assume there are library version mismatches somewhere. As this issue only occurred some weeks ago and not from begin on (I used 20.04 quite long) some lib may have been updated somewhere in the system.
Thanks anyway for your great work.

**Comment by hamiltoncj** [comment]
Thanks for the report.

**Comment by hamiltoncj** [comment]
@cayetanobv This is invariably due to the fact that you are using the wrong PROJ library as others have found out. The reason that you see it right away with Lat Lon Tools is that I initialize a variable that calls the PROJ library when the plugin is initialized.

This is not a Lat Lon Tools problem, but with the PROJ library being used by QGIS.
