### ISSUE TITLE
Multi-Location Zoom display wrong CRS

### ISSUE THREAD

**Issue by gi921120** [NationalSecurityAgency/qgis-latlontools-plugin#67]
Hi there, 

When using the _Multi- Location  Zoom_ window the capture coordinates don't take the custom project CRS. They display the coordinates as Lat Long. I found a work around in the modification of the python files _captureCoordinate.py_ and _util.py_. I replaced the CRS 4326 with my custom project CRS and it works.  It would be handy if you can fix this on future updates. 

Kind regards, 

Giovanny

**Comment by hamiltoncj** [comment]
Closing due to lack of further input.
