### ISSUE TITLE
Google Earth for Web as an external provider

### ISSUE THREAD

**Issue by RW-gis** [NationalSecurityAgency/qgis-latlontools-plugin#68]
Hi - A simple suggestion for an enhancement, to add Google Earth for Web to the list of external map providers (which doesn't require Google Earth to be installed locally). After some searching for an appropriate format, I find that the following seems to work: https://earth.google.com/web/search/{lat},{lon}/

**Comment by hamiltoncj** [comment]
That is a great suggestion. I should have a new release this week or next with this included.

**Comment by hamiltoncj** [comment]
I released Lat Lon Tools 3.6.4 which includes Google Earth for Web.

**Comment by RW-gis** [comment]
Thank you 👍
