### ISSUE TITLE
2.14 and 2.18 throw exception in 0.9

### ISSUE THREAD

**Issue by rduivenvoorde** [NationalSecurityAgency/qgis-latlontools-plugin#7]
RuntimeError: no access to protected functions or signals for objects not created from Python 

Traceback (most recent call last):
  File "~/.qgis2/python/plugins/latlontools/multizoom.py", line 114, in geomChanged
    self.resultsTable.horizontalHeader().resizeSections()
RuntimeError: no access to protected functions or signals for objects not created from Python

**Comment by rduivenvoorde** [comment]
Maybe see: https://github.com/olivierdalang/CadInput/issues/3

And if I comment out the geomChanged connect in line 68, I get another exception when adding a field in settings:

RuntimeError: no access to protected functions or signals for objects not created from Python 
Traceback (most recent call last):
  File "/home/richard/.qgis2/python/plugins/latlontools/settings.py", line 178, in accept
    self.lltools.settingsChanged()
  File "/home/richard/.qgis2/python/plugins/latlontools/latLonTools.py", line 165, in settingsChanged
    self.multiZoomDialog.settingsChanged()
  File "/home/richard/.qgis2/python/plugins/latlontools/multizoom.py", line 90, in settingsChanged
    self.geomChanged()
  File "/home/richard/.qgis2/python/plugins/latlontools/multizoom.py", line 114, in geomChanged
    self.resultsTable.horizontalHeader().resizeSections()
RuntimeError: no access to protected functions or signals for objects not created from Python

So apparently, something here is not useable (in Linux?) 
Will test on Windows too later.

**Comment by rduivenvoorde** [comment]
Not sure if this is a Linux only thingie... I think in my plugins I just resize the last table with something like setStretchLastSection(True).
Instead of 
        #self.resultsTable.horizontalHeader().resizeSections()
        self.resultsTable.horizontalHeader().setStretchLastSection(True)
seems to work, though probably not as good as your solution....

Maybe create the resultsTable in python space?

**Comment by rduivenvoorde** [comment]
in python console: 

from qgis.utils import plugins
p=plugins['latlontools']
p.multiZoomDialog.resultsTable.horizontalHeader().resizeSections()

throws exact this error...

looping over columns and doing:
p.multiZoomDialog.resultsTable.horizontalHeader().setResizeMode(COLNR, QHeaderView.Stretch)
works?

**Comment by hamiltoncj** [comment]
That is a strange error. The computer I am using does not have my full development environment so I can't test the Linux version. Are you saying that

self.resultsTable.horizontalHeader().resizeSections()

always fails or only if I use

self.resultsTable.horizontalHeader().setResizeMode( QHeaderView.Stretch)

and 

self.resultsTable.horizontalHeader().setResizeMode( QHeaderView.Interactive)

**Comment by hamiltoncj** [comment]
I believe I solved the issue.

**Comment by rduivenvoorde** [comment]
hi, checking :-)

FYI: only with self.resultsTable.horizontalHeader().resizeSections()

**Comment by hamiltoncj** [comment]
I just uploaded 0.9.1 and I believe I found a simpler solution. Once
approved let me know how it works.

**Comment by rduivenvoorde** [comment]
yep, error dissappeared.  What about adding adding:

self.resultsTable.horizontalHeader().setStretchLastSection(True) after the setResizeMode lines?

the difference is:

![selection_130](https://cloud.githubusercontent.com/assets/731673/26602405/a8e970aa-4583-11e7-8321-58f4e0a327a3.png)

vs

![selection_131](https://cloud.githubusercontent.com/assets/731673/26602420/af052d12-4583-11e7-9376-dc42c5ba1d7a.png)

I think the last one looks better, and for what I see behaviour is the same
