### ISSUE TITLE
LatLon Tool 3.6.7 not working on QGIS 3.28.2-Firenze

### ISSUE THREAD

**Issue by MixMashAndTinker** [NationalSecurityAgency/qgis-latlontools-plugin#72]
QGIS crashes when trying to install and/or enable the plugin.

Installed versions:

LatLong Tools | 3.6.7

QGIS version | 3.28.2-Firenze | QGIS code revision | b47e00ba60
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.8 (Debian 13.8-0+deb11u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)

Active Python plugins
--
quick_map_services | 0.19.32
QuickOSM | 2.1.1
maplibrary | 1.2
mgrs | 3.0.2
MagneticDeclination | 2.3.1
sagaprovider | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

**Comment by hamiltoncj** [comment]
The problem is most likely the version of PROJ you are using. There have been several issues submitted about this, but it has nothing to do with Lat Lon Tools. Take a look at Issue #71. You can try doing "import pyproj" in the QGIS console. If that fails it is the version of proj you are using.

**Comment by hamiltoncj** [comment]
Closing because of no feedback. The problem is most likely that this user upgraded PROJ and is not using the PROJ associated with his version of QGIS.
