### ISSUE TITLE
Plugin translation

### ISSUE THREAD

**Issue by jeremieprudhomme** [NationalSecurityAgency/qgis-latlontools-plugin#73]
Hello, 

Would it be possible to consider having the plugin translated in other languages ?
For example with a system where users can translate texts in their mother tongue.

I could consider translate it to french.

**Comment by hamiltoncj** [comment]
Yes, that can be done. I am starting to work on getting all the strings prepared for it.

**Comment by hamiltoncj** [comment]
@jeremieprudhomme I believe that I have everything set up to begin the French translation. There is now a directory i18n with the file latlonTools_fr.ts. That is the file that needs to be edited with your French translation. Do you know how to do this? I have never done it myself, but I think QtDesigner has tools to assist with it. It wouldn't surprise me if I missed a few strings that I will need to go back and make available for translation.

**Comment by jeremieprudhomme** [comment]
@hamiltoncj Thanks for your quick answer. I never used this. I don't know how it works. I started yesterday to complete the latlonTools_fr.ts file. Several remarks so far : 

- texts are not ordered by menu in the plugin, so it is not easy to know where is the text, I can only search based on the .py filename. So I'm not sure to be 100% correct when I don't have the context.
- you often have the text "coordinate" (singular). I don't know in english but in french the word is usually used plural (coordinates = coordonnées in french). When used in the singular form, it means one of the elements, e.g. only the x or the y. I am therefore not sure if I must translate it to singular or plural depending on the context (only x or y needed or both)
- the translation file refers the original text in english and not an ID so I wonder how it will work if you change the english text... you will need to update it in each translation files ?
- I am not sure what means the type="unfinished" in the file, do you know ?
- Did you follow a process like the one described in [this answer](https://stackoverflow.com/a/40864882) ? In the [Hello(tr) link](https://doc.qt.io/qt-5/qtlinguist-hellotr-example.html) it is written "The .ts translation source format is designed for use during the application's development."

**Comment by jeremieprudhomme** [comment]
About the coordinate singular/plural, I chose to always use the plural exectp when it is about one coordinate only (X or Y or Z).
About the unfinished, from what I read it is only used when the translation has not been validated, do I deleted them as I found in other projects. I hope you are confident enough in my translations 🙂

As written in the PR https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/pull/74
```
All french translations are done.
Some english sources had typo, I corrected them in their original file and in the latlonTools_fr.ts file in source.
```

**Comment by hamiltoncj** [comment]
@jeremieprudhomme Attached is a beta plugin that includes the translation. Uninstall your existing Lat Lon Tools and install this one by using Install from ZIP in Plugins->Manage and Install plugins. Assuming you system locale is French it will automatically display as French. If you need to you can go Preferences->Options and select the General tab on the left and set "User Interface translation" to francais.
[latlontools-3.6.9_beta.zip](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/files/10839701/latlontools-3.6.9_beta.zip)

Before I release this version please check to make sure it is working correctly and you are satisfied with the translation.

**Comment by jeremieprudhomme** [comment]
Sorry, I did not know about that tool. Thank you!
I used it to check translations and I found I missed some items.
I updated the file and created the PR https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/pull/75.

The translation is working great !
Although I don't have the possibility to translate the list of external map providers already set in the tool. Only useful for "Google Earth (if installed)".

**Comment by hamiltoncj** [comment]
See my note with the pull request. It needs redoing. I missed the map providers, but it might be best to do a pull request of the current .ts file and then I can update the map providers and regenerate the .ts file.

**Comment by hamiltoncj** [comment]
I have already updated the map provider code, but I wont regenerate the .ts file until you have done your next pull request. When you do your translation with the .ts file, make sure you use the latest one that is in the repo. That file is automatically generated, but updated with the contents of the last file.

**Comment by jeremieprudhomme** [comment]
I saw you merged the PR after my correction.
Let me know when you have regenerated the .ts with map providers.

**Comment by hamiltoncj** [comment]
I have regenerated the .ts file.

**Comment by jeremieprudhomme** [comment]
I updated the .ts file wit Qt Linguist.

**Comment by jeremieprudhomme** [comment]
To answer your question in PR https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/pull/76#issuecomment-1450069145 it is QT Linguist which changes the degree symbols and others in the source value

**Comment by hamiltoncj** [comment]
It looks like there may be a problem with the version of Qt Translate you are using and the version of Qt QGIS is using. When I run pylupdate5 on your translation code is has issues with some of the lines and that is why we are getting the obsolete and then untranslated entries. Attached are the problem lines.
[error_messages.txt](https://github.com/NationalSecurityAgency/qgis-latlontools-plugin/files/10862118/error_messages.txt)

I am using QGIS 3.28.3 and it uses Qt 5.15.3. I wonder if there is something incompatible with the Qt Translate you are using. Yours is producing a header tag of 'TS version="2.1"' pylupdate5 is producing a header tag of 'TS version="2.0"'.

Although I can use the .ts file you generated without a problem when running "lrelease latlonTools_fr.ts" to produce the .qm file, I will need to run pylupdate5 every time I make a change in my code so it is probably best to figure this out now. Can you try and install an older version of Qt Translate? Make sure it is Qt version 5 and not Qt version 6.

**Comment by jeremieprudhomme** [comment]
The Qt Linguist indicated in Help > About Qt
`This program uses Qt version 5.12.2.`

Not version 6 so.

Maybe an option somewhere regarding how to encode the degree symbol.
Or an option for the version 2.1/2.0.

I'll try to check.

**Comment by hamiltoncj** [comment]
Hmmm... That dismisses that idea. I tried using \xB0 for the degree symbol and it works exactly the same as using the ascii degree symbol. I also tried resaving the settings dialog box with Qt Designer, but it didn't change the file at all. All the strings that have the degree symbol in it are the ones that have a problem. I am starting to think there may be a bug in pylupdate5 on how it handles the degree symbol.

**Comment by hamiltoncj** [comment]
Just to let you know I did not figure out hot to work with the strings that contained the degree symbol, but I went ahead and released the plugin. There are 6 strings that will be untranslated. I have a further complication that my new supervisor will not allow me to work on anymore community requests and has basically pulled me off of QGIS development other than fixing bugs.

**Comment by jeremieprudhomme** [comment]
Thank you for the feedback, too bad you won't be able to work on this anymore :(
Nevertheless, we now have a FR translation of almost every string and that's good news 👍
