### ISSUE TITLE
Lat Lon Tools expression to be used in array foreach for Multi-polygon

### ISSUE THREAD

**Issue by roelsantiago** [NationalSecurityAgency/qgis-latlontools-plugin#80]
I've been working on  digitizing for Aerodrome Mapping Data. My concern is if the formula (see below) can be expanded for multi-polygon (with exterior and interior rings), this used-case is for digitizing Taxi Holding Position Markings. How to tweak the below expression to handle exterior and interior ring?

replace (
array_to_string (
array_foreach (
generate_series (1, num_points( $geometry)-1),
ddmmss(y(point_n( $geometry,https://github.com/element)), x(point_n( $geometry,https://github.com/element)), 'yx', 0, '', 'EPSG:3857')
)),
',',''
)

I am expecting the gml code to be something like this (see sample below):

gml:patches xmlns:gml="http://www.opengis.net/gml/3.2">
<gml:PolygonPatch>
<gml:exterior>
<gml:Ring>
<gml:curveMember>
<gml:Curve gml:id="gmlID33" srsName="urn:ogc:def:crs:OGC:1.3:EPSG:4326">
<gml:segments>
<gml:GeodesicString>
<gml:pos>25.2865452301958 51.6067159563806</gml:pos>
<gml:pos>25.286572199708 51.6067995931505</gml:pos>
<gml:pos>25.2864779590838 51.6068572073228</gml:pos>
<gml:pos>25.2864428382699 51.6067550305168</gml:pos>
<gml:pos>25.2865452301958 51.6067159563806</gml:pos>
</gml:GeodesicString>
</gml:segments>
</gml:Curve>
</gml:curveMember>
</gml:Ring>
</gml:exterior>
<gml:interior>
<gml:Ring>
<gml:curveMember>
<gml:Curve gml:id="gmlID33" srsName="urn:ogc:def:crs:OGC:1.3:EPSG:4326">
<gml:segments>
<gml:GeodesicString>
<gml:pos>25.2864695544172 51.6067712563988</gml:pos>
<gml:pos>25.2864871116889 51.6068235315942</gml:pos>
<gml:pos>25.2865506576704 51.6067852826748</gml:pos>
<gml:pos>25.2865399782764 51.6067434732674</gml:pos>
<gml:pos>25.2864695544172 51.6067712563988</gml:pos>
</gml:GeodesicString>
</gml:segments>
</gml:Curve>
</gml:curveMember>
</gml:Ring>
</gml:interior>
</gml:PolygonPatch>
</gml:patches>

Tks in advance!

**Comment by hamiltoncj** [comment]
I am not sure how to help you with this and I am actually only able to fix bugs in the code as I am moving on to other projects. I'm not able to give any support other than that. I don't know how you would do this with expressions, but in python code there is a QgsMultiPolygon multi polygon call and you addGeometry for each polygon you want added.
