### ISSUE TITLE
Using this plugin in a python file.

### ISSUE THREAD

**Issue by TonyJacb** [NationalSecurityAgency/qgis-latlontools-plugin#81]
Greetings! 
Absolutely love this plugin. I am just getting used to PyQGIS and I was wondering whether I can use this plugin especially the ZoomToCoordinate feature inside a python file. I want a python file to feed in the co-ordinates.

**Comment by hamiltoncj** [comment]
Being open source means that you can use code from any of the open source QGIS plugins. The only thing I would caution you about is to not replicate functionality from an existing plugin and publish similar functionality to the plugins.qgis.org repository. That is not liked and you risk having your plugin disapproved or having it puled from the QGIS plugin store. If there is an existing plugin that is close to what you want, the proper thing to do is to work with the developers to add your contributions to their plugin. qgis.org tries to encourage collaboration.

If you are just adapting the code for some other purpose then you can use any of the plugin code to help with your development.

**Comment by TonyJacb** [comment]
The need was for me to use the plugin to plot a point on the map by having the coordinates as the input.
However, I managed to implement the feature without the this plugin.
```python
import qgis
from pyproj import Proj, transform

P3857 = Proj(init='epsg:3857')
P4326 = Proj(init='epsg:4326')

lat = ??
long = ??
x,y = transform(P4326, P3857, long , lat)

fn = "PATH_TO_STORE_THE_SHAPEFILE"

writer = QgsVectorFileWriter(fn, 'UTF-8', layerFields, QgsWkbTypes.Point, QgsCoordinateReferenceSystem("EPSG:3857"), "ESRI Shapefile")

feat = QgsFeature()
feat.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x,y)))
writer.addFeature(feat)

iface.addVectorLayer(fn, '', 'ogr')
del(writer)
```
