### ISSUE TITLE
Copy lat/lon format

### ISSUE THREAD

**Issue by funkenbeachin** [NationalSecurityAgency/qgis-latlontools-plugin#82]
If I right click on a point on the map canvas, select WGS84 I get -123.459095,42.022136 in the clipboard.

In Google Earth, the latlontools box and other apps, the format 42.022136, -123.459095 works.  Would lat, lon be a better format?

**Comment by hamiltoncj** [comment]
Closing because this is it not a part of Lat Lon Tools.
