### ISSUE TITLE
Chinese Translations not work

### ISSUE THREAD

**Issue by liuxsdev** [NationalSecurityAgency/qgis-latlontools-plugin#89]
3.6.15 release version uses an older version of the file `latlonTools_zh.qm` (sha256:b225d849034f664cf5c2b40b30d5a5671f97dbc964317edeaaf7ce582668fd35), the latest `latlonTools_zh.qm` in repository hash is 5855121fe10d27c030c080e92e62a42c966a472fdbe99b15a94564da41d000b5.

Maybe there was an error when packaging the plugin

**Comment by hamiltoncj** [comment]
You are correct. I'm not sure what happened, but suspect that I was bit by AWS. I have uploaded a new version and checked the translation.

**Comment by liuxsdev** [comment]
> You are correct. I'm not sure what happened, but suspect that I was bit by AWS. I have uploaded a new version and checked the translation.

It works now, thank you
